Migrate to extra-data
I honestly doubt they'd care about us redistributing their app, but I
couldn't find a license text to actually verify that.

Nevertheless, to prevent potential headaches for me and/or Flathub,
I've decided to migrate to the extra-data strategy.

diff --git a/br.gov.fazenda.receita.irpf2022.yaml b/br.gov.fazenda.receita.irpf2022.yaml
--- a/br.gov.fazenda.receita.irpf2022.yaml
+++ b/br.gov.fazenda.receita.irpf2022.yaml
@@ -27,41 +27,62 @@ modules:
     build-commands:
       - /usr/lib/sdk/openjdk11/install.sh
 
+  - name: libgnome-stubs
+    no-autogen: true
+    sources:
+      - type: dir
+        path: tools/libgnome-stubs
+
   - name: irpf2022
     buildsystem: simple
-    build-options:
-      env:
-        PATH: /app/bin:/usr/bin:/usr/lib/sdk/openjdk11/bin
     build-commands:
+      - install -Dm755 -t /app/bin apply_extra
       - install -Dm755 -t /app/bin irpf2022
       - install -Dm644 -t /app/share/applications $FLATPAK_ID.desktop
       - install -Dm644 icon-64.png /app/share/icons/hicolor/64x64/apps/$FLATPAK_ID.png
       - install -Dm644 icon-128.png /app/share/icons/hicolor/128x128/apps/$FLATPAK_ID.png
       - install -Dm644 icon-256.png /app/share/icons/hicolor/256x256/apps/$FLATPAK_ID.png
       - install -Dm644 -t /app/share/metainfo $FLATPAK_ID.metainfo.xml
-      - install -Dm644 -t /app/share/$FLATPAK_ID irpf.jar pgd-updater.jar
-      # Patch the NavegadorHtml class in lib-modulos/irpf_gui-basica.jar to fix URLs not opening with the default web browser.
-      - javac -d . NavegadorHtml.java
-      - jar -uf lib-modulos/irpf_gui-basica.jar serpro/ppgd/irpf/gui/NavegadorHtml.class
-      - cp -r --no-preserve=mode help/ lib/ lib-modulos/ /app/share/$FLATPAK_ID
-      # Workaround to make the clickable link on the "About" window open with the default web browser.
-      - ln -s /usr/bin/xdg-open /app/bin/firefox
+      - ln -s /usr/bin/xdg-open /app/bin/firefox # Fixes the clickable link on the "About" window.
     sources:
-      - type: archive
-        url: https://downloadirpf.receita.fazenda.gov.br/irpf/2022/irpf/arquivos/IRPF2022-1.9.zip
-        sha256: be419e51a833112eca3b3c67cacdeaa3cc18e0026a18596a1dc197b00e9c8ede
-        x-checker-data:
-          type: html
-          url: https://downloadirpf.receita.fazenda.gov.br/irpf/2022/irpf/update/latest.xml
-          version-pattern: <pkgver>([\d.]+)</pkgver>
-          url-template: https://downloadirpf.receita.fazenda.gov.br/irpf/2022/irpf/arquivos/IRPF2022-$version.zip
-          is-main-source: true
-      - type: file
-        path: patches/NavegadorHtml.java
+      - type: script
+        dest-filename: apply_extra
+        commands:
+          - set -e
+          - export LC_ALL=C
+          - mkdir share
+          - |
+            bsdtar -C share -xf irpf.zip --strip-components 1 \
+              --include='IRPF*/help' \
+              --include='IRPF*/lib' \
+              --include='IRPF*/lib-modulos' \
+              --include='IRPF*/irpf.jar' \
+              --include='IRPF*/pgd-updater.jar'
+          - rm -f irpf.zip
+          - |
+            for zip in *.zip
+            do
+              bsdtar -C share/lib/resources -xf "${zip}" --strip-components 2
+              rm -f "${zip}"
+            done
+          - chmod -R -x+X share
       - type: script
         dest-filename: irpf2022
         commands:
-          - exec java -jar /app/share/br.gov.fazenda.receita.irpf2022/irpf.jar $@
+          # Briefly explaining the script (for more details, see tools/libgnome-stubs/README.md):
+          #
+          # * -Djdk.gtk.version=2: We use this to "trick" the JRE into lading GTK 2 libraries (which we don't provide), which will
+          #                        fail and make the JRE rely on our libgnome stubs instead (see the 'tools/libgnome-stubs' directory).
+          # * _JAVA_OPTIONS: This env var has to be modified to remove any references to the option above, otherwise the trick we
+          #                  apply above will fail, and will break the single sign-on feature provided by the app.
+          - |
+            unsupported_java_option='-Djdk\.gtk\.version=[[:digit:]]'
+            if [[ "${_JAVA_OPTIONS}" =~ ${unsupported_java_option} ]]
+            then
+              echo "${0}: WARNING: Removing unsupported option '${BASH_REMATCH[0]}' from \$_JAVA_OPTIONS" >&2
+              export _JAVA_OPTIONS="${_JAVA_OPTIONS//${unsupported_java_option}/}"
+            fi
+            exec java -Djdk.gtk.version=2 -jar /app/extra/share/irpf.jar $@
       - type: file
         path: br.gov.fazenda.receita.irpf2022.metainfo.xml
       - type: file
@@ -72,11 +93,15 @@ modules:
         path: icons/icon-128.png
       - type: file
         path: icons/icon-256.png
-
-  - name: irpf_xml
-    buildsystem: simple
-    build-commands:
-      - install -Dm644 *.xml /app/share/$FLATPAK_ID/lib/resources
-    sources:
+      - type: extra-data
+        filename: irpf.zip
+        url: https://downloadirpf.receita.fazenda.gov.br/irpf/2022/irpf/arquivos/IRPF2022-1.9.zip
+        sha256: be419e51a833112eca3b3c67cacdeaa3cc18e0026a18596a1dc197b00e9c8ede
+        size: 50014969
+        x-checker-data:
+          type: html
+          url: https://downloadirpf.receita.fazenda.gov.br/irpf/2022/irpf/update/latest.xml
+          version-pattern: <pkgver>([\d.]+)</pkgver>
+          url-template: https://downloadirpf.receita.fazenda.gov.br/irpf/2022/irpf/arquivos/IRPF2022-$version.zip
+          is-main-source: true
       - generated-sources.yaml
-
